package com.bintrash

import com.google.api.client.auth.oauth2.AuthorizationCodeFlow
import com.google.api.client.auth.oauth2.BearerToken
import com.google.api.client.auth.oauth2.Credential
import com.google.api.client.util.store.FileDataStoreFactory

import com.google.api.client.auth.oauth2.StoredCredential

import com.google.api.client.http.BasicAuthentication

import com.google.api.client.http.GenericUrl

import com.google.api.client.http.javanet.NetHttpTransport




fun main() {
//    val credential = Credential(BearerToken.authorizationHeaderAccessMethod())
//    credential.accessToken = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicmwtY2ljZC1kZXYwMS0yIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMzkzOTNhOThhYTdmZDBjMGY4YzNkOGZmM2FkNGNmYmFlODIxYmFlNiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDNVBwTzl1RmtYVnFvMVxuYkpLQjBTdUNFa2lMalh5RWxGS3krK3dTaG1WZEsrdkpZU1p0bCthVnJ4RlB6b2EwNlU4bUlLcnFPZHF2MmZtL1xuV2dYQ2tJaEhNdjhkVFY5ZEpkS0tZbXVrNlVNY0VNR2FWN2diY2ptQjJ0Nmc5WnZtdnpJU1dlSlltRlhMMk8yNVxuaVlFL3F4UEVPZGxBck1OYzN2QXNvNWtreW5WNVlOTXowNkIxbk5MZFltcTAyU09oMStJL21kZEZ0eTZ5NnM4aVxuTC9mbUhVVGZma3pLMjNXaEFjS1UvQVJSUVRCRUJNeEZOOGJ0SlNWN1o4RzNONFhvSnVCajUrZGNKN3RuY2xHMFxubmhHeU5paWFCY28yVm01NUlIZjA4dlcyUGtnQ1BJVU91cGs0NlZLcU5xN1ovNVhSSld3Mmh4ZWlRa3pob3o2NVxuckhiYzNEZDdBZ01CQUFFQ2dnRUFFekJIbERnaEI3NklkRzdzdGk4ajkwaWhqeU1oZjRlYkVXM3didkxRL29KcVxuM1k5Y3NGbUlkSCtQL0M1Wk1kV1djZmYyL0dXYklPck92ZzJRaElPb09qS0VKQUE4Y3FUL3JDb0p4ZFFMM3VwZ1xuR1BiTDNCRk1UUWFPVjlTdW5qWmhTaGxaZUVmcUMwQkxUNzdOK1U4UUJjYmdSRWQyYlRaWUMvMEpBMlh5eVVIRlxuM0JlNFp4Uk05UUxYcENiNThtd3J5V3FxUEJ6SS8xeVRnWDFGSWhSWkFwNjU4V3VUVFlFQTdhOUFEREs5emhMZVxuOG1aZWphb0w1Mk1rcWpzYThaTUdkdXB5SjZJcGpKRDhQeWQvK1F2OVBkKzRwQkx2NFlITjlzVU94cE82elk3QVxuNGtUWjYxWm10bmlEMnNybXZEaHhsbE9sZk94cy9pRldWUkxQeHhtbXNRS0JnUURsZ0plUk0zUWoycHhIVFlETFxuTHpzMG9BT2xONDl5NGlkVW8xN052YlpwYy9SWnBlOHlKNlRLVFBkYzdCNGx3bFovVVdmQjk0VWpXYlFjTng4YlxubXJTZHV4aGUrSUlzSkNQY3lLUEpXZTZKUVptUTFhVUxHZmdORm9hSTdwTEh3Q3BmczI3c1NuQVNCaG5tRXg0V1xuaTV1dHZuMjI5YWpLaW5rS3dUU083ZmV3M3dLQmdRRE9vZHFGNmZkMVVNUUFmMEZKMXNQZERZZ2hXN0xYWTNJeFxuaVd3SFExSXpoakozZWJBVGtTSk5WRFJOM2c0c3ZkY2p3Qm14bUJ0aTVEaGlKaURSWnFOQnROR0E2M0RTVyt4blxueXlFYlA1R1N3V1ZkM1EwTTBzTmY5aXJhR2lqL2NWbkhNYkx4ZXlVSUpOVTVSM0Z3N0xsM2hTTm5pb05kTUJXL1xuTGhsWkJCVUE1UUtCZ0d5QmJLZUl4U3RDYTByRzJOSzNwTzFQamdtcUNCZFAxenFMOXdHYzVVWmNQVFc1WHlxK1xuVllvVDg0dXFVdUtWVENIcjBmdUIxQitQaExrbVVuM1JtZjFNL012Q0FJRndJTWg4ei9zZG1zcW9DanZRMXJRMVxuOWZIeUtXOUtKSGx1WUZwWTBtUERHZE5ic1JqM0J1MnYyYzIrVjErT0s5eCt0WldoSFFGS2Z5WFBBb0dCQUtscVxuVU1WOUI5UWJEU2l2TFhPQjc0SzlSb0M3TTAyZmpwQUk4UmFmWHJVNThRUytNOXhISVkydlhWYittamFheTlyV1xuOVBvRUVXZ3FZQVF3NkxWblpyRkh0SUgwQjhPaGRKbkJGUHJIU3U2OVBBUVNhbEc2T0Uva2dFdmtLUHNQRDZIZlxuSUswVzMwem5EaDl4Y1JRNk12SklxYmVKL0p5YUFTcUhmR2JjanUvMUFvR0JBSWdSOUhzanVqcldad2Y2d2hIVlxuZlJSWFV6YTFNRXRxZ08raVRHR2VQTGU5cXo4WXZ6bXo0d3lyNGJYOGdkeTEyaitkWlBDbjVSVUZwWjFoMTZOWlxuVCs2dnV0MEtzUnFsSWR2KzIwdXpBbHJNbTNmN1VkTWdVcngwSGFWbHVBSE8vUnFYaG5NdytuNDFEKzFJNlA0N1xuYzZWZVFuY2c5MGlqVWJWTHljK09acXNMXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZG9jcHJvY3N0b3JhZ2VhZG1pbi1hekBybC1jaWNkLWRldjAxLTIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAyMzIzNTU0NzYwMTgzMDc4Nzc0IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9kb2Nwcm9jc3RvcmFnZWFkbWluLWF6JTQwcmwtY2ljZC1kZXYwMS0yLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg=="
//
//    val token = credential.refreshToken
//
//    println(token)

//    AuthorizationCodeFlow.Builder(
//        BearerToken.authorizationHeaderAccessMethod(),
//        NetHttpTransport(),
//        JacksonFactory(),
//        GenericUrl("https://server.example.com/token"),
//        BasicAuthentication("s6BhdRkqt3", "7Fjfp0ZBr1KtDRbnfVdmIw"),
//        "s6BhdRkqt3",
//        "https://server.example.com/authorize"
//    ).setCredentialDataStore(
//        StoredCredential.getDefaultDataStore(
//            FileDataStoreFactory(File("datastoredir"))
//        )
//    )
//        .build()
}